export const perguntasDTO = {
    armazem: {
        "Qualidade no carregamento": [
            "Há o uso de 100% dos EPIs previstos para a execução da tarefa?",
            "Os requisitos de segurança e meio ambiente colocados no DPO são completamente seguidos?",
            "Conferente / Conferente Líder realizou check de qualidade nas empilhadeiras?",
            "Os Itens de qualidade dos veículos SPOT foram conferidos antes do carregamento? se estavam em perfeitas condiçoes?",
            "As baias foram limpas antes de serem carregadas? (Bais livres de sujeiras, plástico, papelão e cacos de vidro)",
            "Conferente/SOA realizou ronda de qualidade no picking antes de começar o carregamento?",
            "Os produtos no picking estão de acordo PZC?",
            "Os produtos do picking estão de acordo regras do FEFO?",
            "O PBR I e II é inspecionado antes de iniciar a montagem do pallet?",
            "O Filme stretch utilizado no carregamento foi suficiente?",
            "A carga de RGB foi utilizado fitilho? (Exceto Litro e Litrinho com 23)",
            "Durante a montagem de pallets foram utilizadas folhas separadoras e/ou chapatex?",
            "Os produtos com problema de qualidade durante a montagem são segregados de imediato?",
            "Conferente realiza giro 360 ao fechar a carga com foco em qualidade?"
        ],
        "Empilhamento": [
            "Há o uso de 100% dos EPIs previstos para a execução da tarefa?",
            "Os requisitos de segurança e meio ambiente colocados no DPO são completamente seguidos?",
            "As empilhadeiras da revenda estão de acordo as premissas de qualidade e segurança?",
            "O produto estava identificado antes de ser empilhado?",
            "Foram identificados produtos diferentes a serem empilhados?",
            "As ruas de produto estavam dentro das linhas de marcação do lote?",
            "Os produtos foram empilhados de forma alinhada? (sem ruas tortas)",
            "As garrafeiras estavam com perfeito encaixe para empilhamento?",
            "Os pallets empilhados ou movimentados estavam filmados ou com fitilho? (exceto Litro)",
            "O empilhamento dos produtos descartavéis segue as premissas de qualidade?",
            "Havia inclinação nos pallets empilhados?",
            "Os pallets/ruas estocadas respeitavam a distância de 50cm de outro pallet ou parede?",
            "Havia caixas de incêndio, saídas de emergência ou faixas de pedestres obstruídas pelo empilhamento?",
            "Os produtos estavam empilhados seguindo o FEFO? (não empilhar data nova em frente a uma data antiga)",
            "Os produtos estavam empilhados de acordo com o padrão de empilhamento por embalagem? (disponível no padrão local)",
            "A curva ABC foi respeitada para o empilhamento do produto? (alto giro perto da saída)",
            "As ruas de produto estavam finalizadas com uma reserva?",
            "Havia vasilhame estocado perto de produto?",
            "Em caso de falta de espaço, houve remanejo de rua para manter o cumprimento de curva ABC e FEFO"
        ],
        "Blitz da Puxada": [
            "Há o uso de 100% dos EPIs previstos para a execução da tarefa? (óculos, luva, colete refletivo, bota e capacete quando aplicável)",
            "Os requisitos de segurança e meio ambiente colocados no DPO são completamente seguidos?",
            "O veículo foi sorteado de acordo os produtos com maior incidência de  reposições externa por falta e avaria do CDD?",
            "COA/SOA foram informados pelo controle sobre o veículo da blitz?",
            "O conferente solicitou o operador para descer o pallet selecionado?",
            "A conferência de toda a carga foi feita de forma cega?",
            "Se o pallet for de retornável, a aferição foi feita no chão com a carga batida?",
            "Se o pallet for de descartável, a aferição foi feita no chão e com a retirada dos lastros?",
            "A aferição foi feita na presença do motorista e de um representante da transportadora? (Para CDDs com empurrada o motorista)",
            "A NRI e o formulário foram preenchidos, e as informações digitadas no sistema?",
            "Em caso de anomalia, foi gerado vale? (Operações com WMS realizar vale manual)",
            "O conferente efetuou o recebimento da carga ao final do processo?"
        ],
        "Montagem de Palete": [
            "Há o uso de 100% dos EPIs previstos para a execução da tarefa? (óculos, luva, colete refletivo, bota e capacete quando aplicável)",
            "Os requisitos de segurança e meio ambiente colocados no DPO são completamente seguidos?",
            "O auxiliar utiliza de WMS para a execução da atividade?",
            "O layout fisico do picking corresponde ao WMS?",
            "O auxiliar segue a orientação de posicionamento do wms?(Operação com RTLS deve verificar se o botão de OK ficou verde)",
            "Auxiliar conferiu código e descrição do produto?",
            "Auxiliar verificou se o SKU em questão esta de acordo o padrão de qualidade?",
            "Após coleta do SKU, auxiliar conferiu a quantidade do produto?",
            "Auxiliar faz o check se a TC está disponivel no sistema e no fisico?",
            "Auxiliar finaliza o pallet somente após dispor o mesmo na TC?",
            "Após finalização do pallet pelo auxiliar o conferente faz check SKU x Quantidade?",
            "Caso encontre um erro de montagem é solicitado a correção de imediato?",
            "O erro de montagem é cadastrado de forma correta no WMS?",
            "A Eficiência de montagem foi superior a 70%?"
        ],
        "Contagem de Estoque": [
            "O armazém parou as movimentações de produtos nas áreas de contagem?",
            "Faz primeiro a contagem do regulador e depois do picking?",
            "Verifica se tem o produto em mais de um local?",
            "Faz o check das embalagens semelhantes?",
            "Quando tem dúvida na contagem de embalagens confusas, faz uma dupla contagem?",
            "Segue o roteiro de contagem?",
            "Verifica se na mesma rua tem diferentes produtos?",
            "Verifica se a rua esta realmente com a reserva? (pode ser uma pirâmide no final)",
            "Verifica se estão movimentando produtos durante a  contagem? (A empilhadeira pode ter guardado parte da carreta ou organizando estoque)",
            "Na digitação, verifica os campos certos para preencher?",
            "As áreas foram finalizadas no WMS?",
            "Controle validou a interface entre WMS e IE? (Todas as áreas finalizadas subiram para o IE)"
        ],
        "Refugo": [
            "Há o uso de 100% dos EPIs previstos para a execução da tarefa? (óculos, luva, colete refletivo, bota e capacete quando aplicável)",
            "Os requisitos de segurança e meio ambiente colocados no DPO são completamente seguidos?",
            "O veículo foi sorteado de acordo com os critérios pré-estabelecidos?",
            "O conferente escolheu o pallet e direcionou para a área de aferição?",
            "O motorista esteve presente na aferição, mas sem interagir diretamente com os inspetores?",
            "A inspeção foi feita em todas as garrafas de todas as garrafeiras do pallet selecionado?",
            "O ajudante utilizou algum método para a aferição além da inspeção visual?",
            "O refugo foi segregado por tipo de ocorrência?",
            "A contagem de cada tipo de refugo foi feita no check de aferição após a inspeção visual de todas as garrafeiras do pallet?",
            "O conferente validou a quantidade de refugo lançada pelo ajudante no palm?"
        ],
        "Repack": [
            "(EQUIPAMENTOS) Existem equipamentos adequados para reembalar os produtos?",
            "(EQUIPAMENTOS) Equipamentos encontram-se em bom estado de conservação?",
            "(EQUIPAMENTOS) Há local segregado com a devida identiﬁcação para os equipamentos?",
            "(EQUIPAMENTOS) Quantidade de equipamentos para embalamento dos produtos é a ideal?",
            "(ÁREA) Acesso a área do Repack é restrita? Há funcionários devidamente identiﬁcados?",
            "(ÁREA) Área do Repack encontra-se limpa e organizada?",
            "(ÁREA) Bancada utilizada para embalamento dos produtos encontra-se limpa?",
            "(ÁREA) Há placas de identiﬁcação na área?",
            "(ÁREA) Produtos identiﬁcados para Repack são devidamente segregados?",
            "(ÁREA) Produtos são segregados por tipo e embalagem?",
            "(QUALIDADE) Os produtos segregados para o Repack encontram-se limpos e sem avarias?",
            "(QUALIDADE) A matéria prima utilizada no Repack é adequada para embalamento? Há segregação e identiﬁcação?",
            "(QUALIDADE) O embalamento dos produtos é feito obedecendo a mesma data de validade?",
            "(QUALIDADE) Há local com água para utilização se necessário na lavagem dos produtos?",
            "(CONTROLE) Unidades avulsas no estoque estão dentro do prazo de validade e em boas condições de comercialização?",
            "(CONTROLE) Há registro dos produtos para produção no Repack identiﬁcando: Tipo, código e descrição?",
            "(EQUIPAMENTOS) Equipamentos em bom estado de conservação?",
            "(EQUIPAMENTOS) Houve substituição, diminuição ou acréscimo de algum equipamento?",
            "(EQUIPAMENTOS) Os equipamentos foram guardados em locais devidamente identiﬁcados?",
            "(ÁREA) Após a produção a área do Repack encontra-se limpa e organizada?",
            "(ÁREA) A bancada utilizada para embalamento dos produtos encontra-se limpa?",
            "(ÁREA) Produtos que tiveram o reembalamento realizado estão devidamente segregados por tipo e embalagem?",
            "(ÁREA) Unidades avulsas foram devidamente identiﬁcados e incorporados ao estoque do Repack?",
            "(QUALIDADE) Matéria prima utilizada para o reembalamento foi suﬁciente?",
            "(QUALIDADE) Matéria prima não utilizada na produção encontra-se devidamente identiﬁcada e segregada?",
            "(QUALIDADE) Os produtos são embalados com a mesma data de validade?",
            "(CONTROLE) Existem unidades avulsas incorporadas ao estoque? As mesmas estão dentro do prazo de validade e em boas condições de comercialização?",
            "(CONTROLE) Existem produtos não retirados do estoque depois de produzidos?",
            "(CONTROLE) Há registro de saída dos produtos produzidos no Repack, identiﬁcando tipo, código e descrição?",
            "(CONTROLE) Há registros dos produtos não aproveitados para reembalamento (avarias, despejo, prazo de validade e etc)?"
        ]
    },
    entrega: {
        "Blitz carregamento": [
            "O motorista finaliza a entrega somente após confirmar pagamento e realizar o check 360º no veículo?",
            "Em caso de dúvida quanto à localização do pdv, o motorista utiliza o gps do aparelho?",
            "O motorista aponta o início da entrega assim que chega no pdv?",
            "O aparelho está em perfeitas condições de uso?",
            "O motorista confere o código do cliente no tracking com a nota fiscal e verifica o endereço da entrega antes do apontamento?",
            "O motorista realiza o fim de rota quando chega no cdd?",
            "Em caso de devolução, o motorista informa no tracking o motivo correto apresentado no pdv?",
            "Em caso de alteração de endereço do pdv, o motorista notifica a central de monitoramento?",
            "O motorista possui carregador veicular?",
            "O palm estava em perfeitas condições no início da jornada?",
            "O motorista verifica se a lista de entrega apresentada no tracking corresponde à rota do dia?",
            "O aparelho estava com carga? Foi carregado durante a noite?",
            "O motorista realizou o login antes de sair do cdd?"
        ],
        "Qualidade na Entrega": [
            "Equipe abre e fecha as baias do caminhão de forma que não haja avaria nos produtos?",
            "Equipe descarrega os produtos evitando que seja rasgado a embalagem, furado, amassado ou quebrado?",
            "Equipe realiza o empilhamento dos produtos no carrinho de entrega de forma que não ultrapasse a altura e capacidade?",
            "Equipe desloca o carrinho de entrega com cuidado para que não haja tombamento ou avaria durante o trajeto caminhão-estoque?",
            "Entrega de produtos sem carrinho é realizada corretamente? Não pode manusear os produtos pela embalagem, deve manusear de forma segura evitando que rasgue a embalagem?",
            "Equipe arruma a carga fracionando os produtos de forma que não haja avaria no transporte devido a freadas e curvas?",
            "Motorista realiza a condução do veículo de forma segura? Evitando freadas e curvas que possam avariar produtos?",
            "Todo palete de mix está protegido por stretch? Mesmo após aberto, deve estar em três lados, somente a frente deve estar aberto.",
            "Todo palete de mix está protegido por forração? Chapatex ou papelão deve estar na base evitando que pregos furem embalagens.",
            "Baias do caminhão estão limpas? Existem cacos de vidro que possam danificar produtos?",
            "Existe devolução por motivo de avaria?",
            "Produtos de devolução estão em boas condições?",
            "Embalagens de papelão (One Way/Importadas) não foram expostas à chuva ou umidade?",
            "Os produtos foram expostos ao sol por longo tempo? (Considerar longo tempo acima de 30 minutos)"
        ],
        "Devolução": [
            "Todos os PDVs estão roteirizados em território compatível com o mapa? Gerando difícil acesso ou falta de tempo para entrega?",
            "Em casos de nota a prazo, a equipe verificou se o boleto está junto com a NFe, antes da saída de rota?",
            "Foi realizado orientação ou alinhamentos referente a horários dos clientes com reincidências de devolução?",
            "Equipe de entrega tem conhecimento sobre os códigos de devolução e seus reais motivos?",
            "Os horários de devolução estão condizentes com a realidade de atendimento do PDV?",
            "Equipe de entrega tem conhecimento de como manusear o aplicativo de entrega?",
            "A equipe planejou a rota, considerando PDVs com restrição de horários de tráfego e de entrada?",
            "Equipe sinalizou o início de entrega no BEES DELIVERY? Conseguiu abrir a rota normalmente?",
            "A equipe conferiu junto ao cliente os produtos, quantidades, preço e forma de pagamento da NF?",
            "A equipe verificou a carga antes de sair da revenda, checando faltas ou avarias?",
            "A equipe utiliza os EPIs durante todo o processo de entrega?",
            "Já no PDV, a equipe verificou os vasilhames antes de iniciar a entrega?",
            "Ao identificar alguma inconformidade seja falta de vasilhame, problema financeiro, ou contato com o cliente, a equipe comunicou imediatamente o time do CME?",
            "Foi respeitado o tempo para tratativas de devolução conforme padrão de tomada de decisão?",
            "A equipe foi informada da tratativa para devolução e foi orientada a como proceder para reverter, repassar ou seguir a rota?",
            "Foi realizada a auditoria das notas, para confirmar os motivos da devolução e garantir a tratativa correta?",
            "Foi passado na matinal os resultados de devolução?",
            "Foi realizada as tratativas e punições para que não haja reincidência?",
            "É tratado devolução em RLP estratificando piores equipes, rotas e vendedores? Discutindo tratativas para garantir que não aconteçam mais?",
            "A devolução é item classificatório para melhor do mês?"
        ],
        "Dispersão KM": [
            "Equipe abre e fecha as baias do caminhão de forma que não haja avaria nos produtos?",
            "Equipe descarregam os produtos evitando que seja rasgado a embalagem, furado, amassado ou quebrado.",
            "Foi autorizado pelo Sup. ou AR e CME para fazer o repasse?",
            "Equipe realizou a rota sem PNP?",
            "CME fez a tratativa da PNP?",
            "Aderência ao tracking é maior de 90%?",
            "Distância de ida e volta do primeiro PDV é menor que 80% do KM previsto?",
            "Todos os PDVs estão com as coordenadas corretas?",
            "Roadshow fez a calibragem semanal dos PDVs?",
            "Houve algum desvio de rota no tracking?",
            "Houve algum desvio de rota no veltrac?"
        ],
        "Liberação": [
            "Equipe está presente na Matinal e sem atrasos?",
            "Matinal foi realizada no tempo previsto?",
            "Motorista/Ajudante realizou a conferência das notas x mapa financeiro?",
            "Equipe se deslocou diretamente para o caminhão no pátio?",
            "Caminhão estava lacrado?",
            "Equipe realizou check do mapa da OCP x mapa nota fiscal financeiro?",
            "Motorista realizou check-list do caminhão?",
            "Equipe realizou a conferência da carga?",
            "A carga estava organizada evitando a necessidade de retorno ao armazém para conferência?",
            "A conferência da carga foi realizada dentro do tempo previsto?",
            "A carga estava completa ou não apresentou anomalia evitando a necessidade de retorno ao armazém?",
            "Caso de retorno ao armazém, o ajudante pegou senha?",
            "Caso de retorno ao armazém, o motorista deslocou o caminhão respeitando plano de tráfego?",
            "Após a re-conferência liberada, a equipe se deslocou até a portaria para saída em rota?",
            "O TML da equipe foi abaixo de 30 min?"
        ],
        "Matinal Distribuição": [
            "Supervisor fez o check de EPIs na entrada da sala?",
            "EE da blitz liberadas da matinal?",
            "Analista fez o check dos aparelhos Tracking e iniciou-os ?",
            "Inicio da matinal no horário correto?",
            "Alguém entrou após o inicio da matinal?",
            "Houve chamada espelhada, max 30 segundos?",
            "Alerta de segurança apresentado conforme TOR?",
            "Resultados D-1 e acumulados apresentados e numeros estão corretos?",
            "Foram desdobrados 2 desafios em nº absoluto, preenchidos com caneta preta?",
            "TTO realizado no tempo?",
            "Foi realizado check de retenção?",
            "Realizado grito de guerra?",
            "Mapas foram entregues fora do horário da matinal (antes ou depois)?",
            "TST participou?"
        ],
        "Prestação de contas": [
            "Há o uso de 100% dos EPIs previstos para a execução da tarefa? (óculos, luva, colete refletivo, bota e capacete quando aplicável)",
            "Os requisitos de segurança e meio ambiente colocados no PO são completamente seguidos?",
            "O Conferente / Analista está treinado para executar a tarefa conforme o padrão? (unidade deve ter a LUP de prestação de contas)",
            "Foi registrado o MPD na portaria? (Garantir abertura das baias, garantir que motorista ou manobrista leve o caminhão até o armazém, equipe deve se dirigir a pé pelo plano de tráfego)",
            "NF's devolvidas na portaria ou confirmado sem devolução? Garantido o processo antes da conferência física/financeira",
            "Existe consignação/comodato no mapa? Conferente e equipe sabem o fluxo para fechamento? (Verificar o conhecimento do manual operacional de fechamento de consignação e comodato)",
            "Carga arrumada? Separado devolução em uma baia; tipos de AG's separados (litro, 1/2, 1/1), segregado veículos para evitar gargalo?",
            "Cofre aberto pelo homem cofre? Garantir abertura em local seguro, preferência com câmeras",
            "Retirado numerário do cofre pelo motorista? 100% de notas, moedas, documentos (canhotos, contratos, consignações, cheques)",
            "Numerários estão organizados e separados para facilitar a conferência?",
            "Motorista prestou contas no financeiro? Entregar todo numerário, cheques, canhotos e contas",
            "Caixa Financeiro fechou mapa? Checar se todos os canhotos estão assinados, garantir assinatura de contratos de comodato, cheques têm que ser cadastrados no promax.",
            "Motorista entregou caminhão para o manobrista? Garantir que o fechamento seja feito pelo ajudante enquanto o motorista fecha o financeiro, ajudante aguardar em local seguro durante descarga, longe da empilhadeira.",
            "Descarregou a carga para conferência? Direcionar a carga para os lotes, formando lotes por equipes onde possam ser auditadas",
            "Veículo sorteado para Refugo e apurado refugo? Segregar vasilhame de no mínimo 1 palete de GFE, garantir o formulário assinado pela equipe da transportadora e digitar anomalias.",
            "Conferente fez a conferência cega? Aferir a carga ativo de giro, devolução, trocas e registrar no promax, o conferente deve conferir a carga no chão. (Chapatex, barril, devolução e trocas) em caso de dúvida no retornável baixar a carga também.",
            "Foi feita reconferência? Havendo diferenças repetir o processo, contagem cega de 100% dos itens.",
            "Gerado vale físico caso necessário? Confirmando diferenças, gerar o vale físico impresso e coletar assinatura do responsável pela carga.",
            "Segregado Produto acabado/ Ativo de Giro/ Trocas? Separar todos os produtos para conciliação e separar o refugo caso a transportadora tenha dúvida poder auditar.",
            "O resultado esperado para este procedimento (tempo, custo, qualidade, produtividade, etc) é atingido com a execução da tarefa pelo operador?",
            "É necessário o Conferente / Analista desenvolver novas habilidades ou aprender procedimentos previstos no Padrão?"
        ],
        "Rotina Básica": [
            "Ao retornar ao caminhão, o ajudante presta contas do numerário/canhotos ao motorista?",
            "Caso o próximo ponto de parada seja próximo, o motorista dirige até ele e o ajudante o encontra lá?",
            "Motorista também realiza entrega?",
            "Equipe arruma a carga de vasilhame vazio, realizando o rodizio das caixas?",
            "Equipe confirma com PDV a entrega apresentada na nota fiscal antes de iniciar a descarga? (produtos, quantidade, valor e forma de pagamento)",
            "Equipe cumpre o procedimento de recebimento de numerário conforme padrão de risco?",
            "Equipe executa o ponto de parada quando possível? (varias entregas simultâneas em um único local de entrega)",
            "Equipe utiliza o carrinho visando aumentar a produtividade? Existem 2 carrinhos disponíveis no caminhão?",
            "Equipe utiliza o tracking de forma correta para garantir a calibragem do road?",
            "Houve repasse na rota? (em caso positivo, explicar o motivo no campo observação e checar se PDV é reincidente nos últimos 60 dias)",
            "Em algum PDV a equipe ficou parada mais de 10 minutos? (aguardando PDV abrir, fila de atendimento ou preenchimento de cheque, etc) (Em caso positivo, explicar o cliente e motivo no campo observação)",
            "É necessário o cadastro de alguma janela de atendimento para clientes específico? (Em caso positivo, informar o cliente e motivos)",
            "Existe alguma dificuldade de descarga em algum PDV? (estacionamento, baia, acesso, etc)",
            "A equipe teve TML abaixo de 30min?",
            "A distância do CDD ao 1º PDV e do último PDV ao CDD está de acordo com o previsto road?",
            "O tempo do CDD ao 1º PDV e do último PDV ao CDD está de acordo com o previsto road?",
            "A sequência do road está adequada de forma a otimizar a rota? (em caso negativo, explicar o motivo no campo observação)",
            "Houve alguma dispersão de tempo de atendimento de algum cliente? (considerar como dispersão acima de 10% e explicar os clientes e motivos no campo observação)",
            "A calibragem do tempo de atendimento dos PDV's foi feita e segue a regra da mediana das últimas 10 entregas?",
            "Existem PDV's com tempo de atendimento zerado no road? (em caso positivo, informar PDVs errados para correção)",
            "A geolocalização da rota bate com a geolocalização calibrada no road?m (em caso negativo, informar PDVs errados para correção)"
        ],
    },
    frota: {
        "Consumo combustível": [
            "O condutor segue as rotas planejadas para otimizar o consumo de combustível do caminhão?",
            "O condutor faz uso adequado do controle de velocidade para economizar combustível durante a rota?",
            "O condutor evita acelerações bruscas e frenagens desnecessárias para melhorar o consumo de combustível?",
            "O condutor mantém uma velocidade constante e eficiente ao longo da rota para economizar combustível?",
            "O condutor desliga o motor durante paradas prolongadas para reduzir o consumo de combustível?",
            "O condutor segue as orientações de economia de combustível fornecidas pela empresa durante a rota?",
            "O condutor relata problemas ou preocupações que possam afetar o consumo de combustível do caminhão durante a rota?",
            "O condutor demonstra interesse em melhorar suas habilidades de direção para reduzir o consumo de combustível?",
            "O funcionário responsável pelo checklist recebe feedback regular sobre sua performance e sugestões de melhoria?",
            "O condutor está disposto a receber feedback e orientações para melhorar o seu desempenho em relação ao consumo de combustível durante as rotas?"
        ],
        "Aderência checklist": [
            "Você sempre realiza o checklist do caminhão/cavalo mecânico antes de iniciar a viagem?",
            "Você verifica se o procedimento foi feito corretamente?",
            "Caso você não faça o checklist, você se sente confiante para seguir rota?",
            "Você está familiarizado com os itens que devem ser verificados durante o checklist do caminhão/cavalo mecânico?",
            "Se identificar algum problema durante o checklist, você toma as medidas necessárias para corrigi-lo ou relata ao motorista?",
            "Você entende a importância do checklist do caminhão/cavalo mecânico para garantir a segurança da viagem?",
            "Em caso de falha mecânica durante a viagem, você consideraria a possibilidade de o problema ter sido causado pela falta de realização do checklist?",
            "Você acredita que a realização adequada do checklist pode prevenir acidentes e problemas mecânicos durante a viagem?",
            "Você tem acesso aos documentos que comprovam a realização do checklist, mesmo quando não é o motorista responsável?"
        ],
        "Tempo socorro": [
            "O motorista tem conhecimento de como deve proceder diante da necessidade de um socorro em rota?",
            "O motorista chegou a contactar de imediato o setor de frota ou seu gestor imediato, para que fosse socorrido em rota?",
            "O motorista foi informado do plano elaborado pelo setor de frota para que seja realizado o devido socorro, caso não haja necessidade do motorista socorrista?",
            "Teve necessidade de avalição de risco para que não fosse necessário o socorro?",
            "A equipe de frota colheu informações imediatas, como: motivo do ocorrido, a distância até o local, equipe, veículo, KM?        ",
            "Houve a necessidade de substituição do veículo? Assim como a transferência da carga?",
            "O socorro excedeu 2hs?"
        ],
        "Milimetragem": [
            "É utilizado algum sistema para coleta de dados dos pneus?",
            "Existe um tempo de intervalo para realizar a calibragem?",
            "Existe um tempo de intervalo para realizar a milimetragem?",
            "Foi realizado o rodízio com 2,5mm?",
            "Foi realizado a movimentação do pneu direcional para o traseiro após os 2,00 mm?",
            "Foi realizado a recapagem do pneu ao chegar à 1,6 mm?",
            "O veículo chegou a ser bloqueado devido a mlimetragem está abaixo da dispersão?",
            "Foi respeitado o intervalo de tempo, Km e troca de pneu direcional para realizar o alinhamento e balanceamento?"
        ],
    },
    Segurança: {
        "Relatos": [
            "Conhece a política de relatos?",
            "Foi treinado para execução de relatos?",
            "Conhece os tipos de relatos apresentados na integração?",
            "Conhece e sabe classificar atos inseguros?",
            "Conhece e sabe classificar as condições inseguras?",
            "Conhece e sabe classificar os acidentes e incidentes?",
            "Domina a execução de relatos no aplicativo Quick gestão?",
            "Possui usuário e senha para entrar no aplicativo Quick?",
            "Recebe feedback mensal dos indicadores críticos estratificados?"
        ],
        "Telemetria": [
            "Motorista conhece a política de segurança relacionado ao sistema de telemetria?",
            "Motorista treinado sobre o monitoramento de telemetria na integração?",
            "Condutor conhece o peso de cada evento descrito no prontuário do condutor?",
            "Veículo está equipado com o sistema de telemetria/GPS? ",
            "O motorista recebe feedback sobre os desvios analisados?",
            "É aplicado as MDTs corretamente para todos os eventos críticos encontrados?",
            "O treinamento anual de direção defensiva do condutor está em dia?",
            "O motorista é recebe reciclagem sobre o sistema após a aplicação das MDTs?",
            "A análise do sistema de telemetria é realizada diariamente? "
        ],
        "Rota critica": [
            "O motorista conhece a política da empresa relacionado a segurança do condutor?",
            "O motorista foi treinado antes de assumir rotas críticas?",
            "O motorista conhece as premissas para rotas críticas?",
            "O motorista sabe mencionar o que é um plano de viagem?",
            "O motorista recebe atualizações das rotas críticas pelo setor de segurança?",
            "As premissas para condutores e veículos de rota crítica são atendidas?",
            "É realizada as inspeções semestralmente das rotas críticas para as devidas atualizações?",
            "As rotas críticas são atualizadas e apresentadas nas reuniões de segurança?",
            "O treinamento anual de direção defensiva do condutor está em dia?"
        ],
        "Segurança no trajeto": [
            "Conhece a política de segurança no trajeto?",
            "Recebeu treinamento sobre segurança no trajeto na integração?",
            "Recebeu treinamento sobre prevenção a violência com ênfase no trânsito?",
            "Recebeu treinamento teórico sobre direção defensiva?",
            "Condutor possui CNH para categoria do veículo?",
            "Condutor participou da última blitz de inspeções veicular?",
            "O condutor recebeu notificação de orientação sobre item irregular?",
            "Condutor comunica a mudança sobre o meio de transporte?",
            "Condutor foi orientado sobre uso dos equipamentos de segurança no trajeto (Cinto, capacete, luvas, etc...)"
        ],
        "Transporte no local de trabalho": [
            "O colaborador conhece a política do transporte seguro no local de trabalho?",
            "Recebeu treinamento adequado sendo capacitados e habilitado para acesso as áreas restritas e controladas?",
            "Conhece as avaliações de riscos das áreas, foram apresentadas na integração?",
            "Foi orientado sobre o plano de tráfego a ser seguido?",
            "A supervisão orienta as equipes sobre desvios de comportamentos inseguros?",
            "O colaborador conhece o limite de velocidade nas dependências da unidade?",
            "A área de carregamento e descarregamento é limitado a presença de pedestres?",
            "É realizado o checklist das empilhadeiras diariamente?",
            "Áreas demarcadas para cumprimento de uma operação segura com redzone, faixas de pedestres e sinalizações?"
        ],
        "Plano de tráfego": [
            "O colaborador conhece o Plano de Tráfego vigente da unidade Ambev?",
            "O plano de tráfego foi apresentado ao colaborador no momento da integração?",
            "O colaborador sabe onde está localizado o mapa com as rotas internas e áreas de risco?",
            "Com que frequência o colaborador participa de treinamentos sobre segurança viária interna?",
            "O colaborador já presenciou alguma situação de risco ou quase acidente envolvendo tráfego interno?",
            "O colaborador conhece o procedimento para reportar uma situação de risco no tráfego?",
            "Com que frequência o colaborador aplica as diretrizes do Plano de Tráfego nas suas atividades?",
            "COLABRADOR CONSEGUE CITAR PELO MENOS DUAS medidas de segurança relacionadas ao plano de tráfego que você mais utiliza durante a sua jornada de trabalho?"
        ],
        "Carga/Descarga e controle de chaves": [
            "COLABORADOR SABE descrever como funciona o processo de carregamento e descarregamento de caminhões aqui na unidade da Ambev?",
            "COLABORADOR SABE Quais são os cuidados obrigatórios que você toma antes de iniciar o carregamento ou descarregamento de um caminhão?",
            "COLABORADOR SABE Quem é o responsável por recolher e guardar as chaves do caminhão durante a operação? E por quê isso é feito?",
            "Existe algum procedimento de travamento ou calçamento do veículo?",
            "COLABORADOR SABE O que deve ser feito se um caminhão estiver posicionado de forma incorreta na doca ou sem sinalização adequada?",
            "Se acontecer alguma anormalidade, como movimentação inesperada do caminhão ou ausência de chave, COLABORADOR SABE TOMAR AS DECISÕES NECESSÁRIAS?",
            "COLABORADOR recebeu algum treinamento ou orientação específica CONHECE O PADRÃO E SABE sobre o controle de chaves e sua importância para a segurança operacional?",
            "As chaves ficam armazenadas em algum local específico durante a operação? COLABORADOR SABE Como é feito esse controle?",
            "COLABORADOR SABE Quais os riscos envolvidos em não recolher a chave do caminhão durante a operação de carga/descarga?",
            "COLABORADOR SABE Você já presenciou alguma situação em que houve falha no controle de chaves? "
        ],
        "Trabalho em Altura": [
            "Você possui o treinamento obrigatório conforme a NR-35 para realizar atividades em altura (acima de 2 metros)?",
            "COLABORADOR SABE Quais são os EPIs obrigatórios para realizar a amarração de cargas em altura, segundo os procedimentos da empresa?",
            "COLABORADOR SABE Quais são os sinais de que um talabarte ou cinturão de segurança está comprometido e não deve ser utilizado?",
            "Você sabe o que é uma “zona de queda” e como ela se aplica no processo de amarração em cima do caminhão?",
            "COLABORADOR SABE Como se posicionaR no caminhão durante a amarração para evitar quedas? Existe orientação da empresa sobre isso?",
            "COLABORADOR SABE Em quais situações a amarração da carga pode ser feita com escada e quando isso não é permitido?",
            "COLABORADOR SABE Quais são os sinais de que um talabarte ou cinturão de segurança está comprometido e não deve ser utilizado?",
            "Ao realizar a amarração de uma carga volumosa ou de difícil acesso, COLABORADOR SABE  quais cuidados extras devem ser tomados para garantir a sua segurança?",
            "COLABORADOR SABE  já presenciou algum colega realizando a amarração de forma insegura?",
            "COLABORADOR SABE  explicar, passo a passo, como realiza a amarração da carga em cima do caminhão de forma segura?"
        ],
        "Reabastecimento de Diesel": [
            "COLABORADOR CONSEGUE  descrever como é o procedimento padrão para o abastecimento de diesel aqui na unidade?",
            "COLABORADOR TEM CONHECIMENTO DOS EPIs obrigatórios que devem ser utilizados durante o abastecimento de diesel E os utiliza sempre?",
            "Antes de iniciar o abastecimento, COLABORADOR SAVE QUAIS AS VERificações de segurança QUE DEVE realizaR no local e no veículo/equipamento QUE SERÁ abastecido?",
            "Existe algum procedimento de bloqueio ou sinalização durante o abastecimento para evitar riscos de ignição ou movimentação de veículos?",
            "Você sabe o que fazer em caso de derramamento de diesel durante o abastecimento E Qual o procedimento de contenção e notificação?",
            "O COLABORADOR SABE EXPLICAR SE O abastecimento deve ser realizado com o motor do veículo ligado ou desligado E SABE JUSTIFICAR O Por quê DE TAL AÇÃO?",
            "COLABORADORE CONHECE O PROCCEDIMENTO DE RELATO  se perceber que a bomba de abastecimento ou a mangueira está com algum vazamento ou defeito?",
            "COLABORADOR SOUBE DIZER SE Existe alguma restrição de uso de celular ou outros equipamentos eletrônicos durante o abastecimento E SABE  explicar o motivo?",
            "COLABORADOR SABE QUAIS AS CONDUTAS QUE DEVE TOMAR em caso de emergência durante o abastecimento, como princípio de incêndio ou contato do diesel com a pele?",
            "COLABORADOR CONSEGUE RELATAR quais são os maiores riscos envolvidos no processo de abastecimento de diesel e como  ajuda a evitá-los no dia a dia?"
        ],
        "Carregamento de Baterias": [
            "Você já recebeu treinamento específico sobre o carregamento seguro de empilhadeiras elétricas  E SABE RELATAR O ASSUNTO que foi abordado nesse treinamento?",
            "COLABORADOR SABE descrever o procedimento correto para carregar uma empilhadeira elétrica aqui na unidade E Quais são as etapas principais?",
            "TEM CONHECIMENTO DE Quais são os EPIs obrigatórios para realizar o carregamento de empilhadeiras elétricas, O MOTIVO DE cada um deles E PORQUE SÃO importanteS?",
            "VOCÊ SABE Como é feita a sinalização da área de carregamento E SE Existe algum cuidado especial com a circulação de pessoas no local?",
            "VOCÊ SABE Qual é a sua primeira ação ao identificar que a empilhadeira precisa ser carregada E SE Existe alguma verificação antes de conectar o carregador?",
            "CASO O carregador apresente um cabo rompido ou aquecimento excessivo VOCÊ SABE O QUE DEVE FAZER E QUEM PROCURAR?",
            "VOCÊ SABE Como é feita a desconexão segura da empilhadeira após o término do carregamento E SE Existe alguma ordem correta para isso?",
            "O COLABORADOR SABE SE A empilhadeira pode ser utilizada imediatamente após o carregamento E Existe algum tempo de espera necessário?",
            "Você sabe qual é a importância da ventilação adequada no ambiente de carregamento de empilhadeiras elétricas?",
            "Se tivesse que orientar um novo colaborador sobre o carregamento seguro da empilhadeira SABE EXPLICAR quais seriam os três principais cuidados que você destacaria?"
        ],
        "Interjornada": [
            "O funcionário demonstra ter consciência do tempo que ele tem ou deveria ter de descanso entre o fim do turno dele hoje e o início do próximo turno? (Ex: ele comenta sobre o tempo curto, ou planeja sua saída para garantir o descanso?)",
            "Como o funcionário reage a uma escala que claramente não oferece as 11 horas de interjornada? Ele questiona, aceita passivamente, ou tenta ajustar de alguma forma?",
            "O funcionário demonstra sinais de fadiga ou exaustão no início do turno, que poderiam indicar uma interjornada insuficiente? (Ex: bocejos frequentes, dificuldade de concentração matinal, irritabilidade atípica).",
            "Em conversas informais ou reuniões, o funcionário expressa a importância do descanso para a própria segurança ou para o bom desempenho da equipe? Ele defende a necessidade das 11 horas de descanso?",
            "O funcionário costuma reportar ou sinalizar quando sua interjornada foi reduzida? Como ele faz isso (diretamente ao supervisor, no ponto, etc.)?",
            "Quando há discussões sobre escalas ou produtividade, o funcionário relaciona a capacidade de entrega com a qualidade do descanso?",
            "Ele se mostra preocupado com a segurança dele e dos colegas caso a interjornada não seja respeitada, especialmente em funções que exigem alta atenção ou operam equipamentos?",
            "Ele demonstra proatividade em sugerir soluções para que as 11 horas de descanso sejam garantidas para todos na equipe?"
        ],
        "Intrajornada": [
            "O funcionário inicia e encerra sua intrajornada (pausa para almoço/descanso) nos horários previstos, ou ele costuma estender/encurtar o período sem justificativa aparente?",
            "Ele demonstra compreender que a pausa é um direito e um momento para descanso, ou a utiliza para resolver questões de trabalho ou outras tarefas não relacionadas ao descanso?",
            "Ele demonstra ter consciência do tempo de intrajornada que lhe é devido, especialmente se a duração varia conforme a jornada (ex: 15 minutos para 6 horas, 1 hora para mais de 6 horas)?",
            "O funcionário verbaliza a importância da pausa para recarregar as energias, melhorar a concentração ou reduzir o estresse durante o dia?",
            "Ele incentiva os colegas a fazerem suas pausas completas, ou demonstra uma cultura de pular o almoço para terminar tarefas?",
            "Após o retorno da intrajornada, o funcionário parece revigorado e mais produtivo, ou permanece com sinais de cansaço ou sobrecarga?",
            "O funcionário demonstra sentir-se pressionado (por demandas de trabalho, colegas ou ambiente) a reduzir ou pular seu intervalo de intrajornada?",
            "O funcionário retorna da intrajornada no tempo correto, ou há uma tendência a estender ou encurtar o período sem necessidade aparente, impactando a equipe ou a própria recuperação?",
            "Em situações de alta demanda, o funcionário sinaliza ao supervisor a dificuldade em realizar a pausa, ou ele simplesmente a ignora e continua trabalhando?"
        ],
        "EPI": [
            "Conhece os procedimentos de segurança sobre os equipamentos de proteção individual EPI?",
            "Recebeu treinamento sobre equipamentos de proteção individual na integração?",
            "Conhece os equipamentos específicos para atividade?",
            "Recebeu uniformes padrão após a integração de segurança?",
            "Recebeu todos os equipamentos de proteção individual para atividade especifica?",
            "É registrado na ficha de entrega de EPIs?",
            "É orientado a realizar a troca dos EPIs quando danificado ou no período de troca?",
            "Áreas estão sinalizadas exigindo o uso de EPIs de forma visível?",
            "Recebeu medidas como advertências ou participou da escolinha de segurança por descumprimento nesse processo?"
        ]
    },
};